- hosts: wsl
  ### Go here to edit variables ###
  vars_files:
    - vars/prerequisite_packages.yml
    - vars/user_environment.yml
  ### Comment out roles you don't need ###
  roles:
    - packages
    - shell
    - workspace
  ### Change to your user! ###
  user: chase
