---
- name: update package list
  become: true
  package:
    update_cache: yes

- name: upgrade all packages
  become: true
  package:
    name: "*"
    state: latest

- name: Install packages
  become: true
  apt:
    name: "{{ prerequisite_packages }}"
