---
- name: Clone dot-files
  shell: | 
    git clone git@github.com:{{ dotfiles_repo }}.git admin
  args:
    chdir: ~/{{ repo_directory }}

- name: Pull latest dot-files
  shell: |
    git checkout {{ dotfiles_branch }}
    git pull
  args:
    chdir: ~/{{ repo_directory }}/admin

- name: Install  dot-files
  shell: "{{ dotfiles_command }}"
  args:
    chdir: ~/{{ repo_directory }}/admin

- name: Run VIM installation
  shell: vim +'PlugInstall --sync' +qa
